Contact draft
sscovil/something-awesome pull request #16
Opened 2017-08-16 23:41 UTC by Keeeeeeeks

Tried to knock out #10

2017-08-17 17:04 UTC, sscovil requested changes
Overall, looks good...but there are a few things that need to be fixed and a few that just aren't necessary. It looks like you worked off of an example or used a form builder, which is fine except you need to be sure to only keep what you need and avoid copying references to files that don't exist in your project. ;-)

2017-08-17 17:04 UTC, sscovil commented on src/public/contact.html
> +              <a href="/about/">About</a>
Invalid `href` value, should be `href="/about.html"`.

2017-08-17 17:04 UTC, sscovil commented on src/public/contact.html
> +              <a href="/contact/">Contact</a>
Invalid `href` value, should be `href="/about.html"`.

2017-08-17 17:04 UTC, sscovil commented on src/public/contact.html
> +              <input type="text" id="name" name="name" value="" placeholder="Jimmy Choo" required="required" autofocus="autofocus" />
You do not need to specify `type="text"`, because that is the default value. Also, you can just use `required` apposed to `required="required"`.

2017-08-17 17:04 UTC, sscovil commented on src/public/contact.html
> +              <input type="subject" id="subject" name="subject" value="" />
Invalid `type`, this should just be a text input (which, as mentioned in my previous comment, is the default type). Also, no need to include the `value` attribute unless you are assigning a default value.

2017-08-17 17:04 UTC, sscovil commented on src/public/contact.html
> +              <textarea id="message" name="message" placeholder="Your message must be greater than 14 charcters" required="required" data-minlength="14"></textarea>
Typo in your placeholder text. Also, why a minimum of 14 characters? That's a very arbitrary length...

2017-08-17 17:04 UTC, sscovil commented on src/public/contact.html
> +              <span id="loading"></span>
What is this `span` tag for?

2017-08-17 17:04 UTC, sscovil commented on src/public/contact.html
> +              <input type="submit" value="Submit" id="submit-button" />
Does this `input` need an `id`?

2017-08-17 17:04 UTC, sscovil commented on src/public/index.html
> +              <a href="/contact.html">Contact</a>
Nice! Don't forget to also fix this in `about.html`. (This is why we're going to use templates and dynamically render our HTML soon...)

2017-08-17 17:04 UTC, sscovil commented on src/public/style.css
> +#contact-form {
CSS is out of scope for #10. Try to stick to the requirements of the issue you are working on. Taking on extra work that is out of scope (often referred to as "boy-scouting") is generally frowned upon when you're working on a team.

2017-08-17 17:04 UTC, sscovil commented on src/public/style.css
> +#success {
Getting a little ahead of ourselves, aren't we? :-)

We're actually going to be re-routing the user to a "Thank You" page upon form submission, so none of this is necessary.

2017-08-17 17:04 UTC, sscovil commented on src/public/style.css
> +    background:#D3EDD3 url(../img/accepted_48.png) no-repeat 405px center;
What file is this `url` referencing?

2017-08-18 03:49 UTC, Keeeeeeeks commented on src/public/contact.html
> +              <textarea id="message" name="message" placeholder="Your message must be greater than 14 charcters" required="required" data-minlength="14"></textarea>
14 was a random number; I felt as though I had to change something to indicate that I didn't just copy/paste (but I did, incorrectly).

2017-08-23 20:29 UTC, Keeeeeeeks commented on src/public/contact.html
> +              <input type="submit" value="Submit" id="submit-button" />
Apparently not; I tested it without `id="submit-button"` and it worked

2017-08-23 20:31 UTC, Keeeeeeeks commented on src/public/style.css
> +    background:#D3EDD3 url(../img/accepted_48.png) no-repeat 405px center;
I'll admit; I copy-pasta'd the style.css pieces that I thought were relevant 😅  

It's been deleted, thanks!

2017-08-24 02:07 UTC, sscovil requested changes
A few more changes...almost there!

2017-08-24 02:07 UTC, sscovil commented on src/public/contact.html
> +            <p id="success">
We won't need this.

2017-08-24 02:07 UTC, sscovil commented on src/public/contact.html
> +            <ul id="errors" class="">
Let's handle form validation in a different issue. For now, we don't need this.

2017-08-24 02:07 UTC, sscovil commented on src/public/contact.html
> +              <input type="text" id="name" name="name" value="" placeholder="Jimmy Choo" autofocus="autofocus" required/>
Default type is text, so you don't need to set it. Also, `autofocus` is like `required` where you don't need to give it a value.

2017-08-24 02:07 UTC, sscovil commented on src/public/style.css
> +#errors {
Let's remove all of this `#errors` styling. We won't need it until we do form validation, and by then we will be using a CSS framework that will provide these styles.

2017-08-24 02:07 UTC, sscovil commented on src/public/style.css
> +/* Remove box shadow firefox, chrome and opera put around required fields. It looks rubbish. */
Let's get rid of everything from here down as well, for the same reason I mentioned above.

2017-08-24 02:07 UTC, sscovil commented on src/public/contact.html
> +              <label for="message">Message: <span class="required">*</span></label>
Looks like you got rid of the CSS for the `.required` class that makes the asterisk red. You should ether kill these spam tags with that class, or add some CSS to make use of them.

2017-08-25 15:35 UTC, sscovil approved these changes

2017-08-25 15:35 UTC, merged